### ISSUE TITLE
Add a specialized register method

### ISSUE THREAD

**Issue by guillep** [rajula96reddy/ClapCommandLineHandler#1]
Right now, registration is done in `ClapCommandLineHandler>>initialize`. While that is handy, it has a main problem: initialize is executed automatically when the code is loaded. So that means that it will silently install itself and maybe break code. People do not expect that "loading the code" magically installs it into the system sometimes. Since this is a critical part of the system, I'd add instead a method `register`

```
ClapCommandLineHandler class>>register
	SessionManager default
		unregisterClassNamed: BasicCommandLineHandler name.
	SessionManager default 
		registerSystemClassNamed: self name
```

**Comment by guillep** [comment]
Also, the current `initialize` method reads as:

```
initialize 
	self startUp: true.
	ActiveSubClassCollection := OrderedCollection new.
	TestSubClassCollection := OrderedCollection new.
	SessionManager default unregisterClassNamed: BasicCommandLineHandler .
	SessionManager default 
		registerSystemClassNamed: self name
```

and there are things that do not work there. Are you sure that you properly tested it? ;)

**Comment by rajula96reddy** [comment]
Yeah makes sense! I will add a register method. And yeah the `initialize` is not unregistering the BasicCommandLineHandler. Sorry for that. Will look into it.
