### ISSUE TITLE
Avoid global state

### ISSUE THREAD

**Issue by guillep** [rajula96reddy/ClapCommandLineHandler#2]
Right now, the classes to use are in two collections in class variables:

```
ActiveSubClassCollection := OrderedCollection new.
TestSubClassCollection := OrderedCollection new.
```

You have to think that class variables are globals, like static java variables. You have to maintain them updated, you have to clean them up, and so on... I'd not use this strategy. Instead, I'd use one instance variable on the instance side. Since you're doing `new` on your `ClapCommandLineHandler` for each activation, you can fill the instance variables at that moment.

**Comment by guillep** [comment]
The same happens with global behaviour. There are some methods that just call the class side. E.g., 

```
ClapCommandLineHandler>> collectSubclasses
	^ ClapCommandLineHandler collectSubclasses.
```

Why not just putting the entire method in the instance side?

**Comment by rajula96reddy** [comment]
Oh! :+1:  I actually thought initializing every time is not the right way. So I made them class variables. I will change the working. :)
